[tool.poetry]
name = "codeinterpreterapi"
version = "0.0.7"
description = "CodeInterpreterAPI is an unofficial and open source python interface for the ChatGPT CodeInterpreter."
authors = ["Shroominic <pleurae-berets.0u@icloud.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
python-dotenv = "^1.0.0"
openai = "^0.27.8"
langchain = "^0.0.232"
codeboxapi = "^0.0.9"

[tool.poetry.extras]
image_support = ["Pillow"]
streamlit_support = ["streamlit"]

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
mypy = "^1.4.1"
black = "^23.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
