[tool.poetry]
name = "codeinterpreterapi"
version = "0.0.10"
authors = ["Shroominic <contact@shroominic.com>"]
license = "MIT"
description = "CodeInterpreterAPI is an (unofficial) open source python interface for the ChatGPT CodeInterpreter."
keywords = ["codeinterpreter", "chatgpt", "codeinterpreterapi", "api", "langchain", "codeboxapi"]
readme = "README.md"
repository = "https://github.com/shroominic/codeinterpreter-api"

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
python-dotenv = "^1"
openai = "^0.27"
langchain = "^0.0.242"
codeboxapi = "^0.0.15"
streamlit = { version = "^1", optional = true }
jupyter-kernel-gateway = { version = "^2", optional = true }
Pillow = { version = "^9", optional = true }

[tool.poetry.extras]
all = ["localbox", "frontend", "image_support"]
localbox = ["jupyter-kernel-gateway"]
frontend = ["streamlit"]
image_support = ["Pillow"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7"
mypy = "^1.4"
black = "^23"
flake8 = "^6"
pre-commit = "^3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
